sqs2sf:
  handler: index.sqs2sfHandler
  timeout: 200
  memory: 128
  source: 'node_modules/@cumulus/api/dist/sfStarter/'
  launchInVpc: true

sqs2sfThrottle:
  handler: index.sqs2sfThrottleHandler
  timeout: 200
  memory: 128
  source: 'node_modules/@cumulus/api/dist/sfStarter/'
  launchInVpc: true
  tables:
    - SemaphoresTable

sns2elasticsearch:
  handler: index.handler
  timeout: 100
  useElasticSearch: '{{es.name}}'
  launchInVpc: true
  memory: 320
  source: 'node_modules/@cumulus/api/dist/indexer/'
  tables:
    - GranulesTable
    - ExecutionsTable
    - PdrsTable
  namedLambdaDeadLetterQueue: true

log2elasticsearch:
  handler: index.logHandler
  timeout: 100
  memory: 320
  useElasticSearch: '{{es.name}}'
  launchInVpc: true
  source: 'node_modules/@cumulus/api/dist/indexer/'
  namedLambdaDeadLetterQueue: true

dbIndexer:
  handler: index.handler
  timeout: 300
  memory: 320
  source: 'node_modules/@cumulus/api/dist/dbIndexer/'
  useElasticSearch: '{{es.name}}'
  tables:
    - FilesTable
  launchInVpc: true
  envs:
    system_bucket: '{{system_bucket}}'
  namedLambdaDeadLetterQueue: true

fallbackConsumer:
  handler: index.handler
  timeout: 100
  memory: 256
  source: 'node_modules/@cumulus/api/dist/messageConsumer/'
  deadletterqueue: kinesisFailure
  launchInVpc: true
  tables:
    - RulesTable
    - CollectionsTable
    - ProvidersTable
  envs:
    system_bucket: '{{system_bucket}}'

jobs:
  handler: index.handler
  timeout: 300
  memory: 320
  useElasticSearch: '{{es.name}}'
  launchInVpc: true
  source: 'node_modules/@cumulus/api/dist/jobs/'
  namedLambdaDeadLetterQueue: true

cleanExecutions:
  handler: index.handler
  timeout: 900
  memory: 192
  source: 'node_modules/@cumulus/api/dist/cleanExecutions/'
  namedLambdaDeadLetterQueue: true
  launchInVpc: true
  tables:
    - ExecutionsTable
  envs:
    nonCompleteExecutionPayloadTimeout: '"{{non_complete_execution_payload_timeout}}"'
    completeExecutionPayloadTimeout: '"{{complete_execution_payload_timeout}}"'
    nonCompleteExecutionPayloadTimeoutDisable: '"{{non_complete_execution_payload_disable}}"'
    completeExecutionPayloadTimeoutDisable: '"{{complete_execution_payload_disable}}"'

# used as custom resource for cloudformation manipulation
CustomBootstrap:
  handler: index.handler
  timeout: 300
  memory: 320
  source: 'node_modules/@cumulus/api/dist/bootstrap/'
  launchInVpc: true
  envs:
    system_bucket: '{{system_bucket}}'

EmsReport:
  handler: index.handler
  timeout: 300
  memory: 320
  source: 'node_modules/@cumulus/api/dist/emsReport/'
  useElasticSearch: '{{es.name}}'
  launchInVpc: true
  envs:
    system_bucket: '{{system_bucket}}'
    ems_provider: '{{ems.provider}}'
  namedLambdaDeadLetterQueue: true

EmsDistributionReport:
  handler: index.handler
  timeout: 300
  memory: 128
  source: 'node_modules/@cumulus/api/dist/emsDistributionReport/'
  launchInVpc: true
  envs:
    LOGS_BUCKET: '{{system_bucket}}'
    REPORTS_BUCKET: '{{system_bucket}}'
    STACK_NAME: '{{stackName}}'

executeMigrations:
  handler: index.handler
  timeout: 300
  useElasticSearch: '{{es.name}}'
  memory: 1024
  source: 'node_modules/@cumulus/api/dist/executeMigrations/'
  launchInVpc: true
  tables:
    - GranulesTable
    - FilesTable
    - ExecutionsTable
    - PdrsTable
    - RulesTable
  envs:
    KinesisInboundEventLogger:
      function: Ref
      value: KinesisInboundEventLoggerLambdaFunction
    system_bucket: '{{system_bucket}}'

messageConsumer:
  handler: index.handler
  timeout: 100
  memory: 256
  source: 'node_modules/@cumulus/api/dist/messageConsumer/'
  launchInVpc: true
  tables:
    - RulesTable
    - CollectionsTable
    - ProvidersTable
  envs:
    system_bucket: '{{system_bucket}}'
    FallbackTopicArn:
      function: Fn::Sub
      value: '${kinesisFallbackSns}'

CreateReconciliationReport:
  handler: index.handler
  source: 'node_modules/@cumulus/api/dist/createReconciliationReport/'
  launchInVpc: true
  memory: 256
  useDistributionApi: true
  tables:
    - CollectionsTable
    - GranulesTable
    - FilesTable
  envs:
    system_bucket: '{{system_bucket}}'
    cmr_provider: '{{cmr.provider}}'
    cmr_client_id: '{{cmr.clientId}}'
    CMR_ENVIRONMENT: '{{cmr.cmrEnvironment}}'
    CMR_LIMIT: '{{cmr.cmrLimit}}'
    CMR_PAGE_SIZE: '{{cmr.cmrPageSize}}'

ScheduleSF:
  description: 'This lambda function is invoked by scheduled rules created via cumulus API'
  handler: index.schedule
  timeout: 100
  memory: 192
  source: 'node_modules/@cumulus/api/dist/sfScheduler/'
  launchInVpc: true
  tables:
    - CollectionsTable
    - ProvidersTable
  namedLambdaDeadLetterQueue: true

BulkDelete:
  handler: index.handler
  source: 'node_modules/@cumulus/api/dist/bulkDelete/'
  launchInVpc: true

KinesisInboundEventLogger:
  handler: index.handler
  timeout: 300
  memory: 128
  source: 'node_modules/@cumulus/api/dist/payloadLogger/'
  launchInVpc: true

KinesisOutboundEventLogger:
  handler: index.handler
  timeout: 300
  memory: 512
  source: 'node_modules/@cumulus/api/dist/payloadLogger/'
  launchInVpc: true

sfSemaphoreDown:
  handler: index.handler
  timeout: 100
  memory: 512
  source: 'node_modules/@cumulus/api/dist/sfSemaphoreDown/'
  launchInVpc: true
  tables:
    - SemaphoresTable
